// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Configuration;
namespace LabHotelManagment.Login_Models;

public partial class Login_Context : DbContext
{
    public Login_Context()
    {
    }

    public Login_Context(DbContextOptions<Login_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Frontend> Frontends { get; set; }

    public virtual DbSet<Kitchen> Kitchens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["Login"].ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Frontend>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK_Table");
        });

        modelBuilder.Entity<Kitchen>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__kitchen__7628B51D2FDAF8B5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}